Repository cosmos/chain-registry, pull requests merged in 2024-02, with the labels that each got.

#3747 Add Panthea EU endpoints for Shentu
  shentu/chain.json
Labels: endpoints

#3750 Added Commercio.Network version 5.1.0
  commercionetwork/chain.json
Labels: chain-upgrade

#3755 Add Panthea EU endpoints for Bitsong
  bitsong/chain.json
Labels: endpoints

#3757 add rpc and rest endpoints to cosmos and osmosis for interstellar lounge
  cosmoshub/chain.json
  osmosis/chain.json
Labels: endpoints

#3712 Upgrade Lum Network to v1.6.4
  lumnetwork/chain.json
Labels: chain-upgrade

#3736 Upgrade Persistence to v10.4.0 and add v10.3.0 to version history
  persistence/chain.json
Labels: chain-upgrade

#3762 Add Panthea EU endpoints for Provenance
  provenance/chain.json
Labels: endpoints

#3768 add Sr20de endpoints for Celestia
  celestia/chain.json
Labels: endpoints

#3726 Add PPNV endpoints to Humans
  humans/chain.json
Labels: endpoints

#3773 feat: update rpc and grpc urls for coreum testnet
  testnets/coreumtestnet/chain.json
Labels: endpoints

#3771 Update Evmos latest v16.0.3 binary information
  evmos/chain.json
Labels: chain-upgrade

#3774 Add Dymension Hub
  dymension/assetlist.json
  dymension/chain.json
  dymension/images/dymension-logo.png
  dymension/images/dymension-logo.svg
Labels: new-chain

#3729 Upgrade Juno to v19
  juno/chain.json
Labels: chain-upgrade

#3777 Remove stale endpoints
  _scripts/remove-stale-endpoints.py
  arkh/chain.json
  assetmantle/chain.json
  aura/chain.json
  bandchain/chain.json
  bluzelle/chain.json
  bostrom/chain.json
  chain4energy/chain.json
  cifer/chain.json
  composable/chain.json
  conscious/chain.json
  cosmoshub/chain.json
  decentr/chain.json
  fetchhub/chain.json
  gitopia/chain.json
  haqq/chain.json
  humans/chain.json
  injective/chain.json
  irisnet/chain.json
  jackal/chain.json
  juno/chain.json
  konstellation/chain.json
  kujira/chain.json
  lumenx/chain.json
  mises/chain.json
  neutron/chain.json
  nois/chain.json
  nolus/chain.json
  nomic/chain.json
  odin/chain.json
  oraichain/chain.json
  osmosis/chain.json
  passage/chain.json
  provenance/chain.json
  quicksilver/chain.json
  realio/chain.json
  rebus/chain.json
  sommelier/chain.json
  source/chain.json
  stargaze/chain.json
  starname/chain.json
  stratos/chain.json
  stride/chain.json
  tenet/chain.json
  teritori/chain.json
  terpnetwork/chain.json
  terra/chain.json
  terra2/chain.json
  uptick/chain.json
  vidulum/chain.json
Labels: endpoints

#3759 Upgrade Quicksilver to v1.4.7
  quicksilver/chain.json
Labels: chain-upgrade

#3782 Add Panthea EU endpoints for Lum Network
  lumnetwork/chain.json
Labels: endpoints

#3783 Add AutoStake dYmension endpoints
  dymension/chain.json
Labels: endpoints

#3784 Add Lavender.Five Nodes APIs to Dymension
  dymension/chain.json
Labels: endpoints

#3785 Add Lavender.Five Nodes seed for Dymension
  dymension/chain.json
Labels: endpoints

#3794 Update chain.json -- Add dymension endpoints
  dymension/chain.json
Labels: endpoints

#3767 Add Avril 14th rpc/grpc/api
  celestia/chain.json
Labels: endpoints

#3816 Add WhisperNode Dymension RPC / API / gRPC / seed
  dymension/chain.json
Labels: endpoints

#3826 add polkachu xion testnet endpoints
  testnets/xiontestnet/chain.json
Labels: endpoints

#3776 Upgrade Omniflix to v2.1
  omniflixhub/chain.json
Labels: chain-upgrade

#3818 Add NODEJUMPER rpc/api/grpc enpoints for Dymension
  dymension/chain.json
Labels: endpoints

#3828 Halt-height upgrade for Juno (v20)
  juno/chain.json
Labels: chain-upgrade

#3831 Remove staking-explorer REST API endpoint from XPLA
  xpla/chain.json
Labels: endpoints

#3832 Update AutoStake moniker on Dymension
  dymension/chain.json
Labels: endpoints

#3834 Upgrade to Sommelier v7
  sommelier/chain.json
Labels: chain-upgrade

#3836 Update #SoloNation Public Node URLs
  coreum/chain.json
Labels: endpoints

#3781 Upgrade Haqq to v1.7.1
  haqq/chain.json
Labels: chain-upgrade

#3835 Upgrade Nolus to v5.0.1
  nolus/chain.json
Labels: chain-upgrade

#3859 Add Wave endpoints for Dymension
  dymension/chain.json
Labels: endpoints

#3860 Add Celestia Resources from FreshSTAKING
  celestia/chain.json
Labels: endpoints

#3839 Update Dymension Endpoints by 🔥STAVR🔥 chain.json
  dymension/chain.json
Labels: endpoints

#3863 Upgrade Haqq to v1.7.2
  haqq/chain.json
Labels: chain-upgrade

#3892 Upgrade Nomic v8.0.0
  nomic/chain.json
Labels: chain-upgrade

#3893 add posthuman rest, rpc.json
  humans/chain.json
Labels: endpoints

#3900 Update Celestia Cumulo endpoints
  celestia/chain.json
Labels: endpoints

#3907 Added public endpoints to Celestia
  celestia/chain.json
Labels: endpoints

#3897 Upgrade Planq to v1.1.0
  planq/chain.json
Labels: chain-upgrade

#3913 Upgrade Nolus to v0.5.2
  nolus/chain.json
Labels: chain-upgrade

#3901 Add Crosnest Endpoints for Osmosis
  osmosis/chain.json
Labels: endpoints

#3872 Upgrade Nibiru to v1.0.1
  nibiru/chain.json
Labels: chain-upgrade

#3920 Add [NODERS]TEAM endpoints to Dymension chain.json
  dymension/chain.json
Labels: endpoints

#3923 Add itrocket endpoints
  testnets/elystestnet/chain.json
Labels: endpoints

#3924 Update add Inter Blockchain Services seeds
  axelar/chain.json
  bandchain/chain.json
  chihuahua/chain.json
  coreum/chain.json
  decentr/chain.json
  dymension/chain.json
  impacthub/chain.json
  kava/chain.json
  kujira/chain.json
  nolus/chain.json
  passage/chain.json
  provenance/chain.json
  quasar/chain.json
  quicksilver/chain.json
  stargaze/chain.json
  teritori/chain.json
Labels: endpoints

#3865 Upgrade Passage to v2.4.0
  passage/chain.json
Labels: chain-upgrade

#3866 Upgrade Omniflix Hub to v3
  omniflixhub/chain.json
Labels: chain-upgrade

#3936 Bitcanna CSDK Patch
  bitcanna/chain.json
Labels: chain-upgrade

#3941 Added public endpoints to Planq
  planq/chain.json
Labels: endpoints

#3942 Add ITRocket services
  testnets/pryzmtestnet/chain.json
Labels: endpoints

#3938 Upgrade Carbon to v2.38.0
  carbon/chain.json
Labels: chain-upgrade

#3912 Upgrade Haqq to v1.7.3
  haqq/chain.json
Labels: chain-upgrade

#3959 Add v3.1.3 to Jackal compatible binaries
  jackal/chain.json
Labels: chain-upgrade

#3960 Add Lavender.Five endpoints to Nibiru
  nibiru/chain.json
Labels: endpoints

#4001 Add Avril14th seed
  celestia/chain.json
Labels: endpoints
