Repository cosmos/chain-registry, pull requests merged in 2024-04, with the labels that each got.

#4235 Upgrade Stride to v21
  stride/chain.json
Labels: chain-upgrade

#4229 Upgrade Nibiru to v1.1.0
  nibiru/chain.json
Labels: chain-upgrade

#4207 Upgrade XPLA to v1_4
  xpla/chain.json
Labels: chain-upgrade

#4239 Add cvn endpoints for Conscious.
  conscious/chain.json
Labels: endpoints

#4247 fixed URL of Orai's genesis and add RPC and seed of Lava network
  lava/chain.json
Labels: endpoints

#4259 Update Persistence chain.json by 🔥STAVR🔥
  persistence/chain.json
Labels: endpoints

#4264 Upgrade Realio to v0.9.0
  realio/chain.json
Labels: chain-upgrade

#4260 add NODERS rpc,api,grpc,jsonrpc
  archway/chain.json
  aura/chain.json
  bandchain/chain.json
  bitsong/chain.json
  celestia/chain.json
  desmos/chain.json
  dymension/chain.json
  empowerchain/chain.json
  gitopia/chain.json
  haqq/chain.json
  humans/chain.json
  injective/chain.json
  jackal/chain.json
  kyve/chain.json
  lambda/chain.json
  osmosis/chain.json
  pylons/chain.json
  quicksilver/chain.json
  realio/chain.json
  rebus/chain.json
  stratos/chain.json
  umee/chain.json
  uptick/chain.json
  zetachain/chain.json
Labels: endpoints

#4243 Add IBC (ImBeCiles) to Osmosis Assets
  osmosis/assetlist.json
  osmosis/images/ibc.png
Labels: ibc-channels

#4249 Upgrade Quicksilver to v1.5.4
  quicksilver/chain.json
Labels: chain-upgrade

#4244 feat: add dhealth chain
  dhealth/assetlist.json
  dhealth/chain.json
  dhealth/images/dhp.png
  dhealth/images/dhp.svg
Labels: new-chain

#4188 Upgrade Impacthub to v3
  impacthub/chain.json
Labels: chain-upgrade

#4285 Update chain.json XPLA by 🔥STAVR🔥
  xpla/chain.json
Labels: endpoints

#4276 🚀 WHEN MOON 🌕 WHEN LAMBO 🔥 Add RPC, API, EVM and Explorer endpoints to Planq
  planq/chain.json
Labels: endpoints

#4294 Upgrade Composable to v6_5_3
  composable/chain.json
Labels: chain-upgrade

#4297 🚀 WHEN MOON 🌕 WHEN LAMBO 🔥 Add RPC, API and Explorer endpoints to Source
  source/chain.json
Labels: endpoints

#4298 🚀 WHEN MOON 🌕 WHEN LAMBO 🔥 Add RPC, API and Explorer endpoints to SGE
  sge/chain.json
Labels: endpoints

#4283 Update of chain.json for Persistence by Antrix Validator
  persistence/chain.json
Labels: endpoints

#4284 Update of chain.json file for Persistence by Antrix Validator
  testnets/persistencetestnet/chain.json
Labels: endpoints

#4306 Update chain.json provenance by 🔥STAVR🔥
  provenance/chain.json
Labels: endpoints

#4311 Update chain.json agoric by 🔥STAVR🔥
  agoric/chain.json
Labels: endpoints

#4312 Update chain.json bitsong by 🔥STAVR🔥
  bitsong/chain.json
Labels: endpoints

#4313 Update chain.json canto by 🔥STAVR🔥
  canto/chain.json
Labels: endpoints

#4314 Update chain.json Composable by 🔥STAVR🔥
  composable/chain.json
Labels: endpoints

#4315 Update chain.json evmos by 🔥STAVR🔥
  evmos/chain.json
Labels: endpoints

#4316 Update chain.json Gravity by 🔥STAVR🔥
  gravitybridge/chain.json
Labels: endpoints

#4317 Update chain.json Meme by 🔥STAVR🔥
  meme/chain.json
Labels: endpoints

#4319 Update chain.json rizon by 🔥STAVR🔥
  rizon/chain.json
Labels: endpoints

#4320 Update chain.json sifchain by 🔥STAVR🔥
  sifchain/chain.json
Labels: endpoints

#4321 Update chain.json terp by 🔥STAVR🔥
  terpnetwork/chain.json
Labels: endpoints

#4282 Upgrade Nibiru to v1.2.0
  nibiru/chain.json
Labels: chain-upgrade

#4334 🚀 WHEN MOON 🌕 WHEN LAMBO 🔥 Add RPC, API and Explorer endpoints to Bitcanna
  bitcanna/chain.json
Labels: endpoints

#4281 Upgrade DYDX to v4.0.0
  dydx/chain.json
Labels: chain-upgrade

#4336 🚀 WHEN MOON 🌕 WHEN LAMBO 🔥 Add RPC, API and Explorer endpoints to ARKH
  arkh/chain.json
Labels: endpoints

#4337 Upgrade Evmos to v17.0.0
  evmos/chain.json
Labels: chain-upgrade

#4331 Added services from CrypTech
  bitcanna/chain.json
Labels: endpoints

#4363 Patch Archway to v6.0.3
  archway/chain.json
Labels: chain-upgrade

#4166 Upgrade Neutron to v3
  neutron/chain.json
Labels: chain-upgrade

#4364 Add version info for BandChain
  bandchain/chain.json
Labels: chain-upgrade

#4365 🚀 WHEN MOON 🌕 WHEN LAMBO 🔥 Add RPC, API and Explorer endpoints to Beezee
  beezee/chain.json
Labels: endpoints

#4366 🚀 WHEN MOON 🌕 WHEN LAMBO 🔥 Add RPC, API and Explorer endpoints to Lum Network
  lumnetwork/chain.json
Labels: endpoints

#4304 add loop chain
  loop/assetlist.json
  loop/chain.json
  loop/images/loop.png
  loop/images/loop.svg
  loop/images/poa.png
  loop/images/poa.svg
Labels: new-chain

#4372 add [NODERS]TEAM endpoints for Andromeda
  andromeda/chain.json
Labels: endpoints

#4379 Update Osmosis to Version v24
  osmosis/chain.json
  osmosis/versions.json
Labels: chain-upgrade

#4401 HTTPS for Lava REST API
  lava/chain.json
Labels: endpoints

#4426 Update cronos's chain.json for v1.2 upgrade
  cronos/chain.json
Labels: chain-upgrade

#4460 Upgrade likecoin to v4.2.0
  likecoin/chain.json
Labels: chain-upgrade

#4371 Upgrade Persistence to v11.9.0
  persistence/chain.json
Labels: chain-upgrade

#4489 Upgrade Cheqd to v2
  cheqd/chain.json
Labels: chain-upgrade

#4493 Upgrade version history for Kava
  kava/chain.json
Labels: chain-upgrade

#4499 add Nibiru endpoints Stake Village
  nibiru/chain.json
Labels: endpoints

#4491 Upgrade Haqq to v1.7.4
  haqq/chain.json
Labels: chain-upgrade

#4490 Upgrade DYDX to v4.1.0
  dydx/chain.json
Labels: chain-upgrade

#4494 Upgrade Kujira to v1.0.2
  kujira/chain.json
Labels: chain-upgrade

#4495 Upgrade Odin to v0.7.12
  odin/chain.json
Labels: chain-upgrade

#4492 Upgrade Juno to v22
  juno/chain.json
Labels: chain-upgrade

#4497 Upgrade Sei to v3.9.0
  sei/chain.json
Labels: chain-upgrade
